#ifndef DEVICEIPINT_EXPORTS_H
#define DEVICEIPINT_EXPORTS_H

#include <../mmss/MMServer/Exports.h>

#ifdef DEVICEIPINT_EXPORTS
#define DEVICEIPINT_DECLSPEC MMSERVER_EXPORT_DECLSPEC
#define DEVICEIPINT_CLASS_DECLSPEC MMSERVER_CLASS_EXPORT_DECLSPEC
#else
#define DEVICEIPINT_DECLSPEC MMSERVER_IMPORT_DECLSPEC
#define DEVICEIPINT_CLASS_DECLSPEC MMSERVER_CLASS_IMPORT_DECLSPEC
#endif // DEVICEIPINT_EXPORTS
#define DEVICEIPINT_TESTABLE_DECLSPEC DEVICEIPINT_CLASS_DECLSPEC
#endif // DEVICEIPINT_EXPORTS_H
