#ifndef GRPC_INCLUDES_H__
#define GRPC_INCLUDES_H__

#include <axxonsoft/bl/acfa/AcfaService.grpc.pb.h>
#include <axxonsoft/bl/archive/ArchiveSupport.grpc.pb.h>
#include <axxonsoft/bl/archive/ArchiveVolumeService.grpc.pb.h>
#include <axxonsoft/bl/audit/Audit.grpc.pb.h>
#include <axxonsoft/bl/auth/Authentication.grpc.pb.h>
#include <axxonsoft/bl/archive/BackupSource.grpc.pb.h>
#include <axxonsoft/bl/cloud/Cloud.grpc.pb.h>
#include <axxonsoft/bl/config/ConfigurationService.grpc.pb.h>
#include <axxonsoft/bl/config/DevicesCatalog.grpc.pb.h>
#include <axxonsoft/bl/config/DynamicParametersService.grpc.pb.h>
#include <axxonsoft/bl/config/FileSystemBrowser.grpc.pb.h>
#include <axxonsoft/bl/discovery/Discovery.grpc.pb.h>
#include <axxonsoft/bl/domain/Domain.grpc.pb.h>
#include <axxonsoft/bl/domain/Domain.Internal.grpc.pb.h>
#include <axxonsoft/bl/domain/DomainManager.grpc.pb.h>
#include <axxonsoft/bl/events/Events.grpc.pb.h>
#include <axxonsoft/bl/security/GlobalPermissions.grpc.pb.h>
#include <axxonsoft/bl/groups/GroupManager.grpc.pb.h>
#include <axxonsoft/bl/heatmap/HeatMap.grpc.pb.h>
#include <axxonsoft/bl/layout/LayoutManager.grpc.pb.h>
#include <axxonsoft/bl/layout/Layouts.Internal.grpc.pb.h>
#include <axxonsoft/bl/license/LicenseService.grpc.pb.h>
#include <axxonsoft/bl/logic/LogicService.grpc.pb.h>
#include <axxonsoft/bl/maps/MapProvider.grpc.pb.h>
#include <axxonsoft/bl/maps/MapService.grpc.pb.h>
#include <axxonsoft/bl/maps/Maps.Internal.grpc.pb.h>
#include <axxonsoft/bl/media/Media.grpc.pb.h>
#include <axxonsoft/bl/media/MediaService.grpc.pb.h>
#include <axxonsoft/bl/maintenance/ConfigurationManager.grpc.pb.h>
#include <axxonsoft/bl/events/Notification.grpc.pb.h>
#include <axxonsoft/bl/events/Notification.Internal.grpc.pb.h>
#include <axxonsoft/bl/security/ObjectsPermissions.grpc.pb.h>
#include <axxonsoft/bl/primitive/Primitives.grpc.pb.h>
#include <axxonsoft/bl/security/SecurityService.grpc.pb.h>
#include <axxonsoft/bl/state/StateControl.grpc.pb.h>
#include <axxonsoft/bl/statistics/Statistics.grpc.pb.h>
#include <axxonsoft/bl/events/EventHistory.grpc.pb.h>
#include <axxonsoft/bl/notifications/EMailNotifier.grpc.pb.h>
#include <axxonsoft/bl/notifications/GSMNotifier.grpc.pb.h>
#include <axxonsoft/bl/ptz/TagAndTrack.grpc.pb.h>
#include <axxonsoft/bl/ptz/Telemetry.grpc.pb.h>
#include <axxonsoft/bl/ptz/TelemetryHelper.grpc.pb.h>
#include <axxonsoft/bl/tz/TimeZonesManager.grpc.pb.h>
#include <axxonsoft/bl/vmda/VMDA.grpc.pb.h>
#include <axxonsoft/bl/realtimeRecognizer/RealtimeRecognizer.grpc.pb.h>
#include <axxonsoft/bl/videowall/Videowall.grpc.pb.h>
#include <axxonsoft/bl/mmexport/ExportService.grpc.pb.h>

#endif // GRPC_INCLUDES_H__
