#ifndef _MMTRANSPORT_EXPORTS_H_
#define _MMTRANSPORT_EXPORTS_H_

#ifdef _MSC_VER
#define MMTRANSPORT_EXPORT_DECLSPEC extern "C" __declspec(dllexport)
#define MMTRANSPORT_IMPORT_DECLSPEC extern "C" __declspec(dllimport)
#define MMTRANSPORT_CLASS_EXPORT_DECLSPEC __declspec(dllexport)
#define MMTRANSPORT_CLASS_IMPORT_DECLSPEC __declspec(dllimport)
#endif // _MSC_VER

#ifdef __GNUC__
#define MMTRANSPORT_EXPORT_DECLSPEC extern "C" __attribute__ ((visibility("default")))
#define MMTRANSPORT_IMPORT_DECLSPEC extern "C"
#define MMTRANSPORT_CLASS_EXPORT_DECLSPEC __attribute__ ((visibility("default")))
#define MMTRANSPORT_CLASS_IMPORT_DECLSPEC 
#endif

#ifdef MMTRANSPORT_EXPORTS
#define MMTRANSPORT_DECLSPEC MMTRANSPORT_EXPORT_DECLSPEC
#define MMTRANSPORT_CLASS_DECLSPEC MMTRANSPORT_CLASS_EXPORT_DECLSPEC
#else
#define MMTRANSPORT_DECLSPEC MMTRANSPORT_IMPORT_DECLSPEC
#define MMTRANSPORT_CLASS_DECLSPEC MMTRANSPORT_CLASS_IMPORT_DECLSPEC
#endif

#endif // _MMTRANSPORT_EXPORTS_H_
